debug = true
ignore_suffixes = ["a.from-edge.looptest.dnstapir.se.", "b.from-edge.looptest.dnstapir.se"]

[nats]
url = "nats://nats:4222"
event_subject = "core-integration-test.events.new_qname"
observation_subject_prefix = "core-integration-test.observations"
private_subject_prefix = "core-integration-test.scratchpad"
seen_domains_subject_prefix = "core-integration-test.internal.seen-domains"
globally_new_bucket = "globally_new"
private_bucket = "tapir-analyse-new-qname"
seen_domains_bucket = "seen_domains"

[cert]
active = false
interval = 0
cert_dir = "/unused"

[api]
active = false
address = "127.0.0.1"
port = "10001"

[libtapir]
debug = true
